apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: msvensso
    name: openjdk18-openshift
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.redhat.io/redhat-openjdk-18/openjdk18-openshift
      from:
        kind: DockerImage
        name: registry.redhat.io/redhat-openjdk-18/openjdk18-openshift
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: msvensso
    name: msvensso
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: msvensso
    name: msvensso
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: msvensso:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: https://github.com/msvensso/msvensso.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: openjdk18-openshift:latest
      type: Source
    triggers:
    - github:
        secret: c9K85txXtbLzCch5G5NF
      type: GitHub
    - generic:
        secret: yciZsL9W3uW0kVwn_vpB
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: msvensso
    name: msvensso
  spec:
    replicas: 1
    selector:
      app: msvensso
      deploymentconfig: msvensso
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: msvensso
          deploymentconfig: msvensso
      spec:
        containers:
        - image: msvensso:latest
          name: msvensso
          ports:
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - msvensso
        from:
          kind: ImageStreamTag
          name: msvensso:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: msvensso
    name: msvensso
  spec:
    ports:
    - name: 8082-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      app: msvensso
      deploymentconfig: msvensso
  status:
    loadBalancer: {}
kind: List
metadata: {}
